name: first
on: [push]
jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: first step of first job
        uses: actions/checkout@v2
      - name: first step of first job
        run: env | sort
  job2:
    name: second job
    runs-on: windows-latest
    steps:
      - name: first step of second job
        uses: actions/checkout@v2
      - name: first step of second job
        run: "Get-ChildItem Env | Sort-Object Name"
